name: 2mins Deployment@V2
on:
  schedule:
    - cron: '*/2 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v2
        with:
          ref: 'main'  # Switch to the 'main' branch

      - name: Set up Git
        run: |
          git config user.name "ashokbuttowski"
          git config user.email "ashokbuttowski@gmail.com"
      
      - name: Fetch changes from 'code' branch
        run: git fetch origin code
      
      - name: Check for changes
        id: check_changes
        run: |
          git log --name-only HEAD..origin/code
      
      - name: Merge changes (if any)
        if: steps.check_changes.outputs.stdout != ''
        run: |
          git rebase origin/code
          git push origin main
      
      - name: No changes to deploy
        if: steps.check_changes.outputs.stdout == ''
        run: echo "No new changes to deploy."
