name: Daily Deployment
on:
  push:
    branches:
      - code
  schedule:
    - cron: "*/2 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: code

      - name: Deploy changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout main
          git merge code --no-edit
          git push origin main
